# Generated by Django 5.2 on 2025-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='comentario_tecnico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
