# Generated by Django 5.2 on 2025-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='secretaria',
            field=models.CharField(default='NÃO DEFINIDO', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='sigla',
            field=models.CharField(default='SEM SIGLA', max_length=20),
            preserve_default=False,
        ),
    ]
