# Generated by Django 5.2 on 2025-08-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0002_setor_secretaria_setor_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='ramal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
