# Generated by Django 6.0.6 on 2026-06-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '0003_alter_setor_ramal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número do Patrimônio')),
                ('descricao', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Manutenção'), ('baixado', 'Baixado'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonios_responsavel', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonios', to='setores.setor')),
            ],
            options={
                'verbose_name': 'Patrimônio',
                'verbose_name_plural': 'Patrimônios',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('criacao', 'Criação'), ('transferencia_setor', 'Transferência de Setor'), ('transferencia_responsavel', 'Transferência de Responsável'), ('alteracao_status', 'Alteração de Status'), ('baixa', 'Baixa'), ('edicao', 'Edição')], max_length=30)),
                ('descricao', models.TextField()),
                ('setor_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('setor_novo', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel_novo', models.CharField(blank=True, max_length=100, null=True)),
                ('status_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('status_novo', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo_baixa', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_patrimonio', to=settings.AUTH_USER_MODEL)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='patrimonio.patrimonio')),
            ],
            options={
                'verbose_name': 'Histórico de Patrimônio',
                'verbose_name_plural': 'Históricos de Patrimônio',
                'ordering': ['-data'],
            },
        ),
    ]
