# Generated by Django 5.2 on 2025-04-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setores.setor')),
            ],
        ),
    ]
